Desafio/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/home/logout', 'LoginController@logout')->name('logout');
//Route::get('/produtos', 'AuthController@produtos')->name('produtos');

//Route::get('produto/login','AuthController@showLoginForm')->name('produtos.login');
//Route::get('produto/logout','AuthController@showLoginForm')->name('produtos.logout');

//Route::post('/produtos/login/do','AuthController@login')->name('produtos.login.do');

Route::resource('produtos', 'ProdutoController');
Route::get('produtos', 'ProdutoController@create')->name('produtos.create');

/*Auth::routes();

Route::get('/produtos/novo', 'ProdutosController@create')->name('produto');*/

Desafio/app/Produto.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class Produto extends Model
{
    protected $fillable = [
        'nome',
        'preco',
        'foto',
        'descricao',
    ];

}

Desafio/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

Desafio/app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{

    public function produtos()
    {
        if(Auth::check() == true) {
            return view('produto.list');
        }
    return redirect() ->route ( 'produtos.login');

    }
    public function showLoginForm()
    {
        return view('produto.formLogin');
    }

    public function login(Request $request)
    {
        if(!filter_var($request->email, FILTER_VALIDATE_EMAIL)){
            return redirect()->back()->withInput()->withErrors(['O email informado não é valido!']);
        }
        var_dump($request->all());

        $credentials = [
            'email'=> $request->email,
            'password'=> $request->password
        ];

        if(Auth::attempt($credentials)){
            return redirect()->route('produtos');
        }
        return redirect()->back()->withInput()->withErrors(['Os dados informados não conferem']);
    }

    public function logout()
    {
        Auth::logout();
        return redirect()-> route('produtos');
    }
}

Desafio/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Desafio/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class  HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

Desafio/app/Http/Controllers/ProdutoController.php
<?php
namespace App\Http\Controllers;
use App\Produto;
use Illuminate\Http\Request;
use Validator;
use Redirect;
use PDF;
class ProdutoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['produtos'] = Produto::orderBy('id','desc')->paginate(10);
        return view('produto.list',$data);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('produto.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nome' => 'required',
            'preco' => 'required',
            'foto' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'descricao' => 'required',
        ]);
        if ($files = $request->file('foto')) {
            $destinationPath = 'public/foto/'; // upload path
            $profileImage = date('YmdHis') . "." . $files->getClientOriginalExtension();
            $files->move($destinationPath, $profileImage);
            $insert['foto'] = "$profileImage";
        }
        $insert['nome'] = $request->get('nome');
        $insert['preco'] = $request->get('preco');
        $insert['descricao'] = $request->get('descricao');
        Produto::insert($request->only('nome','preco', 'descricao', 'foto'));
        return Redirect::to('produtos')->with('sucesso','Otimo! Produto criado corretamente.');
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Produto  $produto
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Produto  $produto
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $where = array('id' => $id);
        $data['preco'] = Produto::where($where)->first();
        return view('produto.edit', $data);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Produto  $produto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nome' => 'required',
            'preco' => 'required',
            'descricao' => 'required',
        ]);
        $update = ['nome' => $request->nome, 'descricao' => $request->descricao];
        if ($files = $request->file('foto')) {
            $destinationPath = 'public/foto/'; // upload path
            $profileImage = date('YmdHis') . "." . $files->getClientOriginalExtension();
            $files->move($destinationPath, $profileImage);
            $update['foto'] = "$profileImage";
        }
        $update['nome'] = $request->get('nome');
        $update['preco'] = $request->get('preco');
        $update['descricao'] = $request->get('descricao');
        Produto::where('id',$id)->update($update);
        return Redirect::to('produtos')->with('sucesso','Otimo! Produto atualizado corretamente');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Produto  $produto
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Produto::where('id',$id)->delete();
        return Redirect::to('produtos')->with('sucesso','Produto deletado corretamente');
    }
}

Desafio/resources/views/home.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Painel de Controle</div>
                <a href="{{ route('produtos.create') }}"> Adicionar Produtos </a>
                <a href="{{ route('logout') }}"> Logout</a>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Desafio/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style>
        body{
            background-color: #25274d;
        }
        .container{
            background: #F8F8FF;
            padding: 4%;
            border-top-left-radius: 0.5rem;
            border-bottom-left-radius: 0.5rem;
        }
    </style>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Registre-se') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

Desafio/resources/views/produto/create.blade.php
@extends('produto.layout')
@section('content')
    <h2 style="margin-top: 12px;" class="text-center">Adicionar Produto</h2>
    <br>
    <form action="{{ route('produtos.store') }}" method="POST" enctype="multipart/form-data" name="add_produto"{{ csrf_field() }}
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Nome</strong>
                    <input type="text" name="nome" class="form-control" placeholder="Nome">
                    <span class="text-danger">{{ $errors->first('nome') }}</span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Preco</strong>
                    <input type="float" name="preco" class="form-control" placeholder="Preco">
                    <span class="text-danger">{{ $errors->first('preco') }}</span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Descrição</strong>
                    <textarea class="form-control" col="4" name="descricao" placeholder="Descricao"></textarea>
                    <span class="text-danger">{{ $errors->first('descricao') }}</span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Foto do produto </strong>
                    <input type="file" name="foto" class="form-control" placeholder="">
                    <span class="text-danger">{{ $errors->first('foto') }}</span>
                </div>
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
        </div>
    </form>
@endsection

Desafio/resources/views/produto/edit.blade.php
@extends('produto.layout')
@section('content')
    <h2 style="margin-top: 12px;" class="text-center">Editar Produto</h2>
    <br>
    <form action="{{ route('produtos.update', $produto_info->id) }}" method="{{ csrf_field() }}">
        @method('PATCH')
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Nome</strong>
                    <input type="text" name="nome" class="form-control" placeholder="Nome" value="{{ $produto_info->nome}}">
                    <span class="text-danger">{{ $errors->first('nome') }}</span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Preco</strong>
                    <input type="text" name="preco" class="form-control" placeholder="Preco" value="{{ $produto_info->preco }}">
                    <span class="text-danger">{{ $errors->first('preco') }}</span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Description</strong>
                    <textarea class="form-control" col="4" name="descricao" placeholder="Enter Description" >{{ $produto_info->descricao }}</textarea>
                    <span class="text-danger">{{ $errors->first('descricao') }}</span>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Foto do Produto</strong>
                    @if($produto_info->foto)
                        <img id="original" src="{{ url('public/foto/'.$produto_info->foto) }}" height="70" width="70">
                    @endif
                    <input type="text" name="foto" class="form-control" placeholder="" value="{{ $produto_info->foto }}">
                    <span class="text-danger">{{ $errors->first('foto') }}</span>
                </div>
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
        </div>
    </form>
@endsection

Desafio/resources/views/produto/formLogin.blade.php
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
        html,
        body{
            height: 100%;
        }
        body{
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #ffffff;
        }

        .form-signin{
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }
        .form-signin .checkbox{
            font-weight: 400;
        }
        .form-signin .form-control{
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }
        .form-signin .form-control:focus{
            z-index: 2;
        }
        .form-signin input[type="email"]{
            margin-bottom: -20px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
        .form-signin input[type="password"]{
            margin-bottom: 15px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
        img{
            max-width: 50%;
            margin-bottom: 30px;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>

</head>
<body>

<form class="form-signin" method="post" action="{{route('produtos.login.do')}}">
    @csrf
    <img src="https://lh3.googleusercontent.com/-Ia95EEt1bJS3jdznRQetWhpn3uuTQxSqdJ6JJjp7TNN6xjkBD-aue0ZGnA1amJaojz_j98=s85" alt="">

    @if($errors->all())
        @foreach($errors->all() as $error)
            <div class="alert alert-danger" role="alert">
                {{$error}}
            </div>
        @endforeach

    @endif

    <label for="email" class="sr-only">Endereço de E-mail</label><br />
    <input type="text" name="email" id="email" class="form-control" placeholder="E-mail" required><br />

    <label for="password" class="sr-only">Senha</label><br />
    <input type="password" name="password" id="password" class="form-control" placeholder="Senha" required><br />
    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
</form>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

Desafio/resources/views/produto/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Aparencia Padrão</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style>
        body{
            background-color: #25274d;
        }
        .container{
            background: #F8F8FF;
            padding: 4%;
            border-top-left-radius: 0.5rem;
            border-bottom-left-radius: 0.5rem;
        }
    </style>
</head>
<body>
<div class="container">
    <br><br><br>
    @yield('content')
</div>
</body>
</html>

Desafio/resources/views/produto/list.blade.php
@extends('produto.layout')
@section('content')
    <a href="{{ route('produtos.create') }}" class="btn btn-success mb-2">Adicionar</a>
    <br>
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered" id="laravel_crud">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Preco</th>
                    <th>Descricao</th>
                    <th>Criado em</th>
                    <td colspan="2">Action</td>
                </tr>
                </thead>
                <tbody>
                @foreach($produtos as $produto)
                    <tr>
                        <td>{{ $produto->id }}</td>
                        <td>{{ $produto->nome }}</td>
                        <td>{{ $produto->preco }}</td>
                        <td>{{ $produto->descricao }}</td>
                        <td>{{ date('Y-m-d', strtotime($produto->created_at)) }}</td>
                        <td><a href="{{ route('produtos.edit',$produto->id)}}" class="btn btn-primary">Editar</a></td>
                        <td>
                            <form action="{{ route('produtos.destroy', $produto->id)}}" method="post">
                                {{ csrf_field() }}
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {!! $produtos->links() !!}
        </div>
    </div>
@endsection